config/routes.rb
Recipes::Application.routes.draw do
  resources :comments
  resources :images
  resource :pages

  resources :recipes do
    resources :comments
    collection do
      get :filter
    end
  end

  resources :sessions
  resources :users do
    resources :recipes
  end

  match 'about' => 'pages#about', via: :get
  match 'account' => 'users#show', via: :get
  match 'login' => 'sessions#new', via: :get, as: :login
  match 'logout' => 'sessions#destroy', via: :get, as: :logout
  match 'most_recent' => 'recipes#most_recent', via: :get
  match 'signup' => 'users#new', via: :get

  root to: 'recipes#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  def self.chronological
    order :created_at
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new comment_params
    @comment.save!
    @recipe = @comment.recipe
    render partial: 'recipes/comments'
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.delete
    render partial: 'all', locals: { comments: @comment.recipe.comments.chronological }
  end

  def edit
    @comment = Comment.find params[:id]
    render partial: 'form', locals: {
      comment: @comment,
      recipe: @comment.recipe
    }
  end

  def new
    @comment = Comment.new
    @comment.user = current_user
    @comment.recipe = Recipe.find(params[:recipe_id]) if params[:recipe_id]
    render partial: 'form', locals: {
      comment: @comment,
      recipe: @comment.recipe
    }
  end

  def update
    @comment = Comment.find params[:id]
    @comment.update_attributes comment_params
    @recipe = @comment.recipe
    render partial: 'recipes/comments'
  end

  private

  def comment_params
    params
    .require(:comment)
    .permit(
      :body,
      :user_id,
      :recipe_id
    )
  end

  def action_allowed?(args = params)
    case args[:action]
    when 'create', 'new'
      current_user
    when 'edit', 'update', 'destroy'
      current_user == Comment.find(args[:id]).user
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_all.html.haml
- comments.each do |comment|
  = render 'comments/show', comment: comment
  %br/

app/views/comments/_form.html.haml
= form_for comment, remote: true, authenticity_token: true do |form|
  = form.hidden_field :recipe_id, value: recipe.id
  = form.hidden_field :user_id, value: comment.user_id
  .form-group
    = form.text_area :body, class: 'form-control', rows: '5'
  .actions
    = form.submit class: 'btn btn-default'

app/views/comments/_show.html.haml
.comment
  %p.comment-body= comment.body
  - if comment.user == current_user
    = link_to edit_comment_path(comment),
      remote: true,
      class: 'edit-comment' do
      = fa_icon "pencil", text: "Edit"
    = link_to comment_path(comment),
      method: 'delete',
      remote: true,
      data: { confirm: 'Delete your comment?' },
      class: 'delete-comment' do
      = fa_icon "times", text: "Delete"

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.erb

app/views/comments/destroy.html.haml
%h1 Comments#destroy
%p Find me in app/views/comments/destroy.html.erb

app/views/comments/edit.html.haml
= render 'form', comment: @comment

app/views/comments/new.html.haml
= form_for @comment do |f|
  = f.label :body
  = f.text_field :body
= link_back, remote: true do
= fa_icon "arrow-left", text: "Back"

app/views/comments/update.html.haml
%h1 Comments#update
%p Find me in app/views/comments/update.html.erb