config/routes.rb
Recipes::Application.routes.draw do
  resources :comments
  resources :images
  resource :pages

  resources :recipes do
    resources :comments
    collection do
      get :filter
    end
  end

  resources :sessions
  resources :users do
    resources :recipes
  end

  match 'about' => 'pages#about', via: :get
  match 'account' => 'users#show', via: :get
  match 'login' => 'sessions#new', via: :get, as: :login
  match 'logout' => 'sessions#destroy', via: :get, as: :logout
  match 'most_recent' => 'recipes#most_recent', via: :get
  match 'signup' => 'users#new', via: :get

  root to: 'recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :images, allow_destroy: true

  self.per_page = 12

  scope :with_keyword, ->(kw='') do
    kw = "%#{kw}%"
    where(
      "title ilike ? OR body ilike ?",
      kw,
      kw
    )
  end

  def has_images?
    images.present?
  end

  def random_image
    @random_image ||= valid_images.sample || Image.blank
  end

  def valid_images
    images.reject(&:valid?).map(&:destroy)
    images
  end

  def random_thumbnail_url
    random_image.thumb.url
  end

  def thumb_title
    if title.length > 20
      "#{title[0..20]}".try :html_safe
    else
      title
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def create
    @recipe = Recipe.new(recipe_params)
    recipes_form

    if @recipe.save
      flash[:success] = "The recipe was successfully created"
      redirect_to @recipe
    else
      flash[:error] = @recipe.errors.full_messages
      render :new
    end
  end

  def destroy
    if recipe.destroy
      flash[:info] = 'The recipe was successfully deleted'
      redirect_to :root
    else
      flash[:error] = 'The recipe could not be deleted.'
      redirect_back
    end
  end

  def edit
    set_recipe
    recipes_form
  end

  def filter
    @recipes = paginated_recipes.with_keyword params[:term]
    render partial: 'all'
  end

  def index
    paginated_recipes
  end

  def new
    @recipe = Recipe.new
  end

  def show
    set_recipe
  end

  def update
    @recipe = recipe
    if @recipe.update(recipe_params)
      flash[:success] = "The recipe was successfully updated"
      redirect_to @recipe
    else
      flash[:error] = @recipe.errors.full_messages
      render :edit
    end
  end

  private

  def recipes
    @recipes = (
      (user.recipes if user) ||
      (Recipe.all)
    ).order(:title)
  end

  def paginated_recipes
    @recipes = recipes.page(params[:page] || 1)
  end

  def set_recipe
    @recipe ||= Recipe.find_by id: params[:id]
    @images ||= @recipe.try(:images)+ [ Image.new ]
    @recipe
  end
  alias_method :recipe, :set_recipe

  def user
    @user ||= User.find_by id: params[:user_id]
  end

  def recipe_params
    params
      .require(:recipe)
      .permit(
    :title,
    :body,
    :user_id,
    images_attributes: [
      :id,
      :data,
      :user_id,
      :recipe_id
    ]
    )
  end

  def action_allowed?(args = params)
    case args[:action]
    when 'create', 'new'
      current_user
    when 'index', 'show', 'add_image', 'filter'
      true
    when 'edit', 'update', 'destroy', 'delete'
      current_user && recipe.user == current_user
    end
  end

  private def recipes_form
    @markdown_tip = <<tip
You can use <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">markdown</a> here.
<br>
<br>
Example:
<br>
<br>
# Ingredients
<br>
- yams
<br>
- alfalfa paste
<br>
<br>
# Directions
<br>
1. This thing
<br>
2. The next thing
tip
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_all.html.haml
= will_paginate @recipes, class: 'pagination col-md-12 col-sm-12 col-xs-12 text-center'
- @recipes.each do |recipe|
  .col-md-3.col-sm-6.col-xs-12
    = link_to recipe, class: 'no-style' do
      .thumbnail
        %h4= recipe.thumb_title
        = image_tag (recipe.random_image.thumb.url || ''), class: 'img-responsive img-thumbnail', style: 'margin-bottom: 9px'
= will_paginate @recipes, class: 'pagination col-md-12 col-sm-12 col-xs-12 text-center'

app/views/recipes/_comments.html.haml
#comments-list.col-md-6
  = render 'comments/all', comments: @recipe.comments.chronological, recipe: @recipe
  - if current_user
    = link_to "/recipes/#{@recipe.id}/comments/new",
      remote: true,
      data: { id: @recipe.id } do
      = fa_icon :plus
      New Comment

app/views/recipes/_form.html.haml
.row
  = form_for @recipe, html: { multipart: true, class: 'recipe-form col-md-8' } do |form|
    - if current_user.admin?
      .form-group
        = form.text_field :user_id, value: @recipe.user_id || current_user.id, class: 'form-control'
    - else
      .form_group
        = form.hidden_field :user_id, value: @recipe.user_id || current_user.id
    .form-group
      = form.text_field :title, placeholder: "Title", class: 'form-control'
    .form-group
      = form.text_area :body,
        placeholder: "Ingredients and Directions",
        rows: "15",
        data: { content: @markdown_tip, rows: "15" },
        class: "form-control",
        id: 'recipe-body'
    = link_to 'Add Image',
      controller: :images,
      action: :new,
      remote: true,
      recipe: @recipe.id
    #image-uploads.form-group
      = form.fields_for :images, @recipe.images do |images_fields|
        .form-group
          %hr/
          = image_tag images_fields.object.data_url
          %br/
          = images_fields.file_field :data, value: images_fields.object.data, class: 'form-control'
          = images_fields.hidden_field :user_id, value: current_user.id
    .actions
      = form.submit class: 'btn btn-default'

app/views/recipes/_image_carousel.html.haml
.col-md-6.col-sm-6.col-xs-12
  #recipe-carousel.carousel.slide
    - if @recipe.images.count > 1
      %ol.carousel-indicators
        - @recipe.images.each_with_index do |image, i|
          %li{class: (image == @recipe.images.first) ? 'active' : '', "data-slide-to" => i, "data-target" => "#recipe-carousel"}
    -# Carousel items
    .carousel-inner
      - @recipe.images.each do |image|
        %div{class: "item #{(image == @recipe.images.first) ? 'active' : ''}"}
          = image_tag image.data_url, class: 'img-responsive'
    -# Carousel nav
    - if @recipe.images.count > 1
      %a.left.carousel-control{"data-slide" => "prev", :href => "#recipe-carousel"}
        %span.glyphicon.glyphicon-chevron-left
      %a.right.carousel-control{"data-slide" => "next", :href => "#recipe-carousel"}
        %span.glyphicon.glyphicon-chevron-right

app/views/recipes/edit.html.haml
- legend 'New recipe'
= render 'form'
= link_to @recipe do
  %i.icon-ban-circle
  Cancel
= link_to @recipe, method: :delete do
  %i.icon-remove
  Delete

app/views/recipes/index.html.haml
= render 'shared/github_ribbon'
.container
  #recipes-partial.col-md-12.center
    = render 'all'

app/views/recipes/new.html.haml
- legend 'New recipe'
= render 'form'
= link_to recipes_path do
  %i.icon-arrow-left
  Back

app/views/recipes/show.html.haml
- if @recipe.images.present?
  = render 'image_carousel'
.col-md-6.col-sm-6.col-xs-12
  = legend @recipe.title
.col-md-6.col-sm-6.col-xs-12
  = md @recipe.body
.col-md-12.col-sm-12.col-xs-12
  = link_to :root do
    = fa_icon "arrow-left", text: "Back"
  - if current_user && @recipe.user == current_user
    = link_to edit_recipe_path(@recipe) do
      = fa_icon "pencil", text: "Edit Recipe"
#comments.col-md-12.col-sm-12.col-xs-12.container
  = legend 'Comments'
  = render 'comments'