config/routes.rb
Recipes::Application.routes.draw do
  resources :comments
  resources :images
  resource :pages

  resources :recipes do
    resources :comments
    collection do
      get :filter
    end
  end

  resources :sessions
  resources :users do
    resources :recipes
  end

  match 'about' => 'pages#about', via: :get
  match 'account' => 'users#show', via: :get
  match 'login' => 'sessions#new', via: :get, as: :login
  match 'logout' => 'sessions#destroy', via: :get, as: :logout
  match 'most_recent' => 'recipes#most_recent', via: :get
  match 'signup' => 'users#new', via: :get

  root to: 'recipes#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :images
  has_many :recipes
  has_many :comments, dependent: :destroy

  validates :email,
    presence: true,
    uniqueness: true,
    format: {
      with: /.+@.+\..+/,
      message: 'must be the correct format'
    }
  validates :password, unless: -> { password.blank? },
    format: {
      with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*(_|[^\w]|\d)).+\z/,
      message: 'must meet the security requirements'
    },
    length: { minimum: 6 }

  def self.login(email, password)
    User.find_by(email: email).try(:authenticate, password)
  end

  def admin?
    admin == 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "The user was successfully created"
      login_with_session(@user)
      redirect_to :account
    else
      render :new
    end
  end

  def show
    set_user
  end

  def update
    set_user

    if @user.update(user_params)
      flash[:success] = 'User successfully updated'
      render :show
    else
      render :edit
    end
  end

  def destroy
    set_user
    @user.destroy
    flash[:info] = 'User deleted'
    redirect_to :root
  end

  def index
    @users = User.order :email
  end

  def new
    @user = User.new
  end

  def edit
    set_user
  end

  def delete
    set_user
  end

  private

  def set_user
    @user ||= User.find_by(id: params[:id]) || current_user
  end
  alias_method :user, :set_user

  def user_params
    params.require(:user).permit!
  end

  def action_allowed?(args = params)
    case args[:action]
    when 'show', 'edit', 'update', 'delete', 'destroy'
      current_user == user
    when 'new', 'create'
      true
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= render 'shared/errors', model: @user
= form_for @user, class: 'form-horizontal' do |f|
  .form-group.input-group
    %span.input-group-addon
      = fa_icon 'envelope'
    = f.text_field :email, placeholder: "email", class: 'form-control'
  .form-group.input-group
    %span.input-group-addon
      = fa_icon 'key'
    = f.password_field :password,
      placeholder: "password",
      title: 'At least one upper case, one lower case, and one non-letter',
      class: "instant-tooltip form-control",
      'data-container' => 'body'
  .form-group.input-group
    %span.input-group-addon
      = fa_icon 'key'
    = f.password_field :password_confirmation,
      placeholder: "password_confirmation",
      title: 'At least one upper case, one lower case, and one non-letter',
      class: "instant-tooltip form-control",
      'data-container' => 'body'
  .actions
    = f.submit class: 'btn'

app/views/users/delete.html.haml
- legend 'Are you sure you want to delete this user?'
= form_for @user, method: :delete do |f|
  = submit_tag 'Delete', class: 'btn btn-danger'

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.haml
%h1 Editing user
.col-md-6
  = render 'form'
  = link_back do
    = fa_icon 'arrow-left', text: 'Back'
  = link_to @user do
    = fa_icon 'ban', text: 'Cancel'
  = link_to @user, method: :delete, confirm: 'Delete your account?' do
    = fa_icon 'times', text: 'Delete'

app/views/users/index.html.haml
- legend 'All Users'
%table.table.table-hover
  %thead
    %tr
      %th Id
      %th Email
  %tbody
    - @users.each do |user|
      %tr.table-link
        %td= user.id
        %td= link_to user.email, user, class: 'no-style button-link'
%br/
= link_to new_user_path do
  %i.icon-plus-sign
  New User

app/views/users/new.html.haml
- legend 'New user'
.col-md-6
  = render 'form'
  = link_to :root do
    = fa_icon 'arrow-left', text: 'Back'

app/views/users/show.html.haml
%p#notice= notice
- legend @user.email
.span11
  = link_to 'Your Recipes', user_recipes_path(@user)
%br/
%br/
= link_to :root do
  = fa_icon 'arrow-left', text: 'Back'
= link_to edit_user_path(@user) do
  = fa_icon 'pencil', text: 'Edit'