config/routes.rb
Recipes::Application.routes.draw do
  resources :comments
  resources :images
  resource :pages

  resources :recipes do
    resources :comments
    collection do
      get :filter
    end
  end

  resources :sessions
  resources :users do
    resources :recipes
  end

  match 'about' => 'pages#about', via: :get
  match 'account' => 'users#show', via: :get
  match 'login' => 'sessions#new', via: :get, as: :login
  match 'logout' => 'sessions#destroy', via: :get, as: :logout
  match 'most_recent' => 'recipes#most_recent', via: :get
  match 'signup' => 'users#new', via: :get

  root to: 'recipes#index'
end

app/views/shared/_about_me.html.haml
.span4
  - legend 'About me'
  %p
    = md File.read('app/assets/docs/about_me.txt')

app/views/shared/_errors.html.haml
- if model.errors.any?
  .alert.alert-warning.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
    %strong
      - if model.try :error_header
        = pluralize(model.errors.count, "error")
        = model.error_header
      - else
        = pluralize(model.errors.count, "error")
        prohibited this
        \#{model.class.name.downcase} from being saved:
    %ul
      - model.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_messages.html.haml
- flash.each do |key, values|
  - values = [values] unless values.respond_to? :each
  - values.each do |value|
    %div{:class => "alert alert-dismissable alert-#{flash_class(key)}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}
        \&times;
      = value

app/views/shared/_github_ribbon.html.haml
%img{:alt => "Fork me on GitHub", :src => "https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png", :style => "position: absolute; top: 52px; right: 0; border: 0; z-index: 1", :usemap => "#github-ribbon-map"}/
%map{:name => "github-ribbon-map"}
  %area{:coords => "148, 0, 15, 0, 148, 132", :href => "https://github.com/akofink/akrecipes", :shape => "poly", :target => "_blank"}/

app/views/shared/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50335913-1', 'akrecipes.herokuapp.com');
  ga('send', 'pageview');

app/views/shared/_header.html.haml
%nav
  .navbar.navbar-default{:role => "navigation"}
    .container
      .navbar-header.col-md-4.col-sm-3
        = button_tag nil, class: 'btn btn-xs pull-right task_status navbar-toggle', data: { toggle: 'collapse', target: '.navbar-ex1-collapse' } do
          = fa_icon 'bars'
          %span.sr-only Toggle navigation
        = link_to 'akRecipes', :root, class: 'navbar-brand', id: 'logo'
      .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav.col-md-4.col-sm-4
          - if @recipes
            %li
              = form_tag({ controller: :recipes, action: :index }, { class: 'navbar-form' }) do
                .form-group
                  = text_field_tag :query, nil, placeholder: 'filter recipes', class: 'form-control text-center', id: 'recipes-search'
        %ul.nav.navbar-nav.navbar-right.col-md-4.col-sm-5
          - if current_user
            %li= link_to 'New Recipe', new_recipe_path
            %li= link_to 'Logout', :logout
            %li= link_to 'Account', :account
          - else
            %li= link_to 'Login', :login
            %li= link_to 'Sign Up', :signup

app/views/shared/_info.html.haml
- if flash[:info].present?
  .alert.alert-info
    %button.close{"data-dismiss" => "alert", :type => "button"} &times;
    %strong= flash[:info].join('<br>').html_safe

app/views/shared/_success.html.haml
- if flash[:success].present?
  .alert.alert-success
    %button.close{"data-dismiss" => "alert", :type => "button"} &times;
    %strong= flash[:success].join('<br>').html_safe